name: $(BuildID)
trigger: none
pr: none
schedules:
- cron: "0 17 * * 2"
  displayName: Weekly Tuesday release
  branches:
    include:
    - master
  always: true
parameters:
- name: dry_run
  type: boolean
  default: false


stages:
- stage: create_release_commits
  displayName: Create release commits
  jobs:
  - template: jobs/release/create-release-commits.yml

- stage: build_wheels
  displayName: Build wheels
  jobs:
  - template: jobs/release/build-wheels.yml

- stage: verify_wheels
  displayName: Verify wheels
  jobs:
  - template: jobs/release/verify.yml

- stage: build_api_docs
  displayName: Build API Documentation
  jobs:
  - template: jobs/release/build-api-docs.yml
  dependsOn:
  - build_wheels

- stage: publish_release_commits
  displayName: Publish release commits
  jobs:
  - template: jobs/release/publish-release-commits.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}
  dependsOn:
  - build_api_docs
  - verify_wheels

- stage: publish_api_docs
  displayName: Publish API Documentation
  jobs:
  - template: jobs/release/publish-api-docs.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}
  dependsOn:
  - build_api_docs
  - verify_wheels

- stage: upload_pypi
  displayName: Upload packages to PyPI
  jobs:
  - template: jobs/release/upload-to-pypi.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}
  dependsOn:
  - build_api_docs
  - verify_wheels
