jobs:
- job: make_release_tags
  displayName: Create release tags
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml
    parameters:
      git: true

  - task: PythonScript@0
    displayName: Checkout all repos
    inputs:
      scriptSource: filePath
      scriptPath: scripts/checkout_all.py

  - bash: scripts/make_release_commits.sh
    displayName: Make release commits

  - task: PublishPipelineArtifact@1
    displayName: Publish repos artifact
    inputs:
      artifactName: repos
      targetPath: repos

  - bash: scripts/create_release_artifact.sh
    displayName: Create release artifact

  - task: PublishPipelineArtifact@1
    displayName: Publish release.yml
    inputs:
      artifactName: release.yml
      targetPath: release.yml

  - bash: scripts/create_sdist.sh
    displayName: Create sdists

  - task: PublishPipelineArtifact@1
    displayName: Publish sdist pacakges
    inputs:
      artifactName: sdist
      targetPath: sdist
