parameters:
  container_image: angr/ci:2

jobs:
- job: lint
  displayName: Lint
  pool:
    vmImage: ubuntu-18.04
  container:
    image: ${{ parameters.container_image }}
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: "build_archive"
      targetPath: .

  - script: /root/scripts/azure-lint.sh
    displayName: Run linter
