parameters:
  nightly: false
  container_image: angr/ci:2

jobs:
- job: build_linux
  displayName: Build on Linux
  pool: Default
  container:
    image: ${{ parameters.container_image }}
  steps:
  - checkout: none

  - ${{ if eq(parameters.nightly, true) }}:
    - script: /root/scripts/azure-build.sh nightly
      displayName: Build nightly
  - ${{ if eq(parameters.nightly, false) }}:
    - script: /root/scripts/azure-build.sh
      displayName: Build standard

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "build_archive"
      targetPath: ./build.tar.gz
